<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <OutputType>WinExe</OutputType>
    <ReleaseVersion>0.9.2</ReleaseVersion>
    <ApplicationIcon>Images\AppIcon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>ScoobyRom</AssemblyTitle>
    <Description>Car control unit (ECU, TCU) firmware (ROM) data visualization viewer and metadata editor.
License: GPL v3</Description>
    <Product>ScoobyRom</Product>
    <Copyright>© 2011-2024 SubaruDieselCrew</Copyright>
    <AssemblyVersion>0.9.3.*</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <OutputPath>bin\Debug</OutputPath>
    <ConsolePause>false</ConsolePause>
    <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
    <Commandlineparameters>defaultRom.rom</Commandlineparameters>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugType>none</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <ConsolePause>false</ConsolePause>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <OutputPath>bin\Debug</OutputPath>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DebugType>none</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <Commandlineparameters>defaultRom.rom</Commandlineparameters>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
	<Reference Include="Florence">
      <HintPath>vendor\Florence.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="gtk-gui\gui.stetic">
      <LogicalName>gui.stetic</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\AppIcon.png">
      <Gettext-ScanForTranslations>false</Gettext-ScanForTranslations>
      <LogicalName>Images.AppIcon.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ScoobyRom.desktop">
      <DeployService-TargetDirectoryId>Linux.DesktopApplications</DeployService-TargetDirectoryId>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="gnuplot_Table2D.plt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="gnuplot_Table3D.plt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="COPYING.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="GtkWidgets\" />
    <Folder Include="UIGtk\" />
    <Folder Include="DataFile\" />
    <Folder Include="Plot\" />
    <Folder Include="vendor\" />
    <Folder Include="Util\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Images\AppIcon.svg">
      <Gettext-ScanForTranslations>false</Gettext-ScanForTranslations>
    </None>
    <None Include="vendor\NPlot.dll">
      <Gettext-ScanForTranslations>false</Gettext-ScanForTranslations>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LibScoobyRom\LibScoobyRom.csproj" />
  </ItemGroup>
  <ProjectExtensions>
    <MonoDevelop>
      <Properties>
        <GtkDesignInfo generateGettext="False" />
      </Properties>
    </MonoDevelop>
  </ProjectExtensions>
  <ItemGroup>
    <PackageReference Include="gtksharp" Version="3.24.24.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
  </ItemGroup>
</Project>