<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Subaru</RootNamespace>
    <ReleaseVersion>0.9.3</ReleaseVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>LiScoobyRom</AssemblyTitle>
    <Description>Denso ROM and misc related functionality.</Description>
    <Copyright>2011-2015 SubaruDieselCrew</Copyright>
    <AssemblyVersion>0.8.2.*</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Debug</OutputPath>
    <ConsolePause>false</ConsolePause>
    <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <ConsolePause>false</ConsolePause>
    <SignAssembly>true</SignAssembly>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Tables\" />
    <Folder Include="Util\" />
    <Folder Include="IDA\" />
  </ItemGroup>
  <!--
  <ItemGroup>
    <Content Include="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="COPYING.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  -->
</Project>